name: Build and Deploy Evidence Dashboard

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Evidence dashboard
      env:
        FLIGHT_SQL_ENDPOINT: ${{ secrets.FLIGHT_SQL_ENDPOINT || 'https://your-production-endpoint.com/query' }}
      run: npm run build
      
    - name: Deploy to S3 (Optional)
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        if [ -n "$S3_BUCKET" ]; then
          aws s3 sync ./build/ s3://$S3_BUCKET/ --delete
          echo "Deployed to S3: $S3_BUCKET"
        else
          echo "S3 deployment skipped - no S3_BUCKET configured"
          echo "Built files available in ./build/"
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: evidence-dashboard-build
        path: build/
        retention-days: 30